# -*- coding: utf-8 -*-
"""Magnum_Opus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yX0FqIpVUl6LIIf5c68OvJqorA4bYfsR
"""

!apt-get -qq install openslide-tools
!pip install -q openslide-python scikit-image gdown lifelines

import os, glob, json, time, random, pickle, shutil
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

CANCER_TYPES = {
    "BLCA": {"gdc_project": "TCGA-BLCA", "cbioportal_study": "blca_tcga_pan_can_atlas_2018"},
    "LUAD": {"gdc_project": "TCGA-LUAD", "cbioportal_study": "luad_tcga_pan_can_atlas_2018"},
    "LUSC": {"gdc_project": "TCGA-LUSC", "cbioportal_study": "lusc_tcga_pan_can_atlas_2018"},
}

# --- paper parameters (Sections III-B, IV-A, IV-B) ---
PATCH_SIZE        = 256    # 256 x 256 pixels
TARGET_MAG        = 20     # 20X objective magnification, level 1
PATCH_TARGET      = 2000   # candidate patches per WSI before clustering
K_CLUSTERS        = 50     # K = 50
PATCHES_PER_CLUST = 10     # S = 10, so N = K * S = 500
G_AUGMENT         = 80     # G = 80 repeated selections per WSI
MIN_TISSUE_COVER  = 0.5    # patch must be >= 50% inside the tissue mask
MASK_LEVEL_TARGET = 32     # build the tissue mask ~32x downsampled

SLIDES_PER_CANCER = 5      # raise toward "all" as compute allows
DATAHUB = "/content/datahub/public"
WORK    = "/content/pamt"
os.makedirs(WORK, exist_ok=True)

# authors' released artifacts
DINO_WEIGHTS_GDRIVE_ID = "1m1o5JNiMu7z3DTCCi9lx1NOuZpl_wHtQ"
PATHWAY_MATRIX_FOLDER  = "https://drive.google.com/drive/folders/1WvRA6OF1lbreXPfof4qbv1Y4tP_wabBA"

DINO_CKPT = f"{WORK}/dino_pamt_20cancer.pth"

if not os.path.exists(DINO_CKPT):
    !gdown --id {DINO_WEIGHTS_GDRIVE_ID} -O {DINO_CKPT}

if not os.path.exists(f"{WORK}/pathways_genes_matrix.csv"):
    !gdown --folder {PATHWAY_MATRIX_FOLDER} -O {WORK}/authors_data
    # the folder layout may nest; surface the CSV we need
    for hit in glob.glob(f"{WORK}/authors_data/**/pathways_genes_matrix.csv", recursive=True):
        shutil.copy(hit, f"{WORK}/pathways_genes_matrix.csv")
        break

print("DINO checkpoint :", os.path.exists(DINO_CKPT),
      f"({os.path.getsize(DINO_CKPT)/1e6:.0f} MB)" if os.path.exists(DINO_CKPT) else "")
print("pathway matrix  :", os.path.exists(f"{WORK}/pathways_genes_matrix.csv"))

!git lfs install --skip-smudge
if not os.path.exists("/content/datahub"):
    !git clone --depth 1 --filter=blob:none https://github.com/cBioPortal/datahub.git /content/datahub

_targets = ",".join(
    f"public/{cfg['cbioportal_study']}/{f}"
    for cfg in CANCER_TYPES.values()
    for f in ("data_mrna_seq_v2_rsem.txt", "data_clinical_patient.txt")
)
!git -C /content/datahub -c lfs.fetchexclude="" lfs pull -I "{_targets}"

from sklearn.preprocessing import StandardScaler

gene_data, survival_data = {}, {}

for cancer, cfg in CANCER_TYPES.items():
    study = cfg["cbioportal_study"]
    print(f"===== {cancer} =====")

    expr = pd.read_csv(f"{DATAHUB}/{study}/data_mrna_seq_v2_rsem.txt",
                       sep="\t", low_memory=False)

    matrix = (expr.dropna(subset=["Hugo_Symbol"])
                  .drop_duplicates(subset="Hugo_Symbol")
                  .set_index("Hugo_Symbol")
                  .drop(columns=["Entrez_Gene_Id"])
                  .T)
    matrix.index = matrix.index.str[:12]                    # sample -> patient ID

    n_dup = int(matrix.index.duplicated().sum())
    if n_dup:
        print(f"  dropping {n_dup} duplicate patient IDs (keeping first sample)")
        matrix = matrix[~matrix.index.duplicated(keep="first")]

    matrix = matrix.apply(pd.to_numeric, errors="coerce").fillna(0.0)

    log_expr = np.log2(matrix + 1)
    gene_data[cancer] = pd.DataFrame(
        StandardScaler().fit_transform(log_expr),
        index=log_expr.index, columns=log_expr.columns)

    # --- survival labels: T (time) and S (event indicator, 1 = death observed) ---
    clin = pd.read_csv(f"{DATAHUB}/{study}/data_clinical_patient.txt",
                       sep="\t", comment="#")
    surv = clin[["PATIENT_ID", "OS_MONTHS", "OS_STATUS"]].dropna().copy()
    surv["event"] = surv["OS_STATUS"].astype(str).str.startswith("1").astype(int)
    surv["time_days"] = pd.to_numeric(surv["OS_MONTHS"], errors="coerce") * 30.44
    surv = surv.dropna(subset=["time_days"]).set_index("PATIENT_ID")
    survival_data[cancer] = surv[["time_days", "event"]]

    print(f"  expression : {gene_data[cancer].shape[0]} patients x "
          f"{gene_data[cancer].shape[1]} genes")
    print(f"  survival   : {len(surv)} patients, {surv['event'].sum()} deaths observed\n")

PATHWAY_CSV = f"{WORK}/pathways_genes_matrix.csv"

if os.path.exists(PATHWAY_CSV):
    pg = pd.read_csv(PATHWAY_CSV, index_col=0)
    print(f"authors' pathway-gene matrix: {pg.shape}  (paper: 186 x 5245)")
    pathway_names   = pg.index.tolist()
    paper_gene_list = pg.columns.tolist()
    E_prime_full    = pg.values.astype(np.float32)
else:
    raise FileNotFoundError(
        "pathways_genes_matrix.csv not found. Download it from\n"
        f"  {PATHWAY_MATRIX_FOLDER}\n"
        "and place it at " + PATHWAY_CSV)


def align_E_prime(cancer):
    """Intersect the authors' gene list with genes present on the RSEM platform.

    Returns E' restricted to shared genes, plus the aligned expression frame.
    Some of the paper's 5245 genes are absent from TCGA's 20531-gene platform;
    those columns are dropped rather than zero-filled, and the count is reported.
    """
    expr = gene_data[cancer]
    shared = [g for g in paper_gene_list if g in expr.columns]
    missing = len(paper_gene_list) - len(shared)

    col_idx = [paper_gene_list.index(g) for g in shared]
    E_prime = E_prime_full[:, col_idx]
    expr_aligned = expr[shared]

    print(f"{cancer}: E' {E_prime.shape} | {missing} of {len(paper_gene_list)} "
          f"paper genes absent from platform | empty pathway rows "
          f"{int((E_prime.sum(1) == 0).sum())}")
    return E_prime, expr_aligned


pathway_matrices, gene_aligned = {}, {}
for cancer in CANCER_TYPES:
    E_prime, expr_aligned = align_E_prime(cancer)
    pathway_matrices[cancer] = E_prime
    gene_aligned[cancer] = expr_aligned


def build_pathway_tokens(cancer, patient_id):
    """E = E' (.) e  ->  (186, n_genes). Row m is pathway token Pm (Section III-A)."""
    e = gene_aligned[cancer].loc[patient_id].values.astype(np.float32)
    return pathway_matrices[cancer] * e[np.newaxis, :]


pid = gene_aligned["BLCA"].index[0]
E = build_pathway_tokens("BLCA", pid)
members = pathway_matrices["BLCA"][0] == 1
assert np.all(E[0][~members] == 0), "non-member genes must be zeroed"
print(f"\nVERIFIED  pathway tokens for {pid}: {E.shape}, "
      f"non-zero {(E != 0).sum()}/{E.size}")

GDC_FILES = "https://api.gdc.cancer.gov/files"
GDC_DATA  = "https://api.gdc.cancer.gov/data"

slide_manifests = {}

for cancer, cfg in CANCER_TYPES.items():
    filters = {
        "op": "and",
        "content": [
            {"op": "in", "content": {"field": "cases.project.project_id",
                                     "value": [cfg["gdc_project"]]}},
            {"op": "in", "content": {"field": "files.data_format", "value": ["SVS"]}},
            {"op": "in", "content": {"field": "files.experimental_strategy",
                                     "value": ["Diagnostic Slide"]}},
        ],
    }
    resp = requests.get(GDC_FILES, params={
        "filters": json.dumps(filters),
        "format": "JSON",
        "fields": "file_id,file_name,file_size,cases.submitter_id",
        "size": "10000",
    })
    hits = resp.json()["data"]["hits"]

    rows = []
    for h in hits:
        cases = h.get("cases") or []
        if not cases:
            continue
        rows.append({
            "patient_id": cases[0]["submitter_id"],
            "file_id":    h["file_id"],
            "file_name":  h["file_name"],
            "size_mb":    h["file_size"] / 1e6,
        })
    df = pd.DataFrame(rows)

    # keep patients that have BOTH gene expression and survival labels
    have_gene = set(gene_aligned[cancer].index) & set(survival_data[cancer].index)
    df = df[df["patient_id"].isin(have_gene)]
    df = df.drop_duplicates(subset="patient_id", keep="first")

    # CHANGE 10: random sample, not smallest-first
    if len(df) > SLIDES_PER_CANCER:
        df = df.sample(n=SLIDES_PER_CANCER, random_state=SEED)

    slide_manifests[cancer] = df
    print(f"{cancer}: {len(hits)} diagnostic slides on GDC | "
          f"{len(have_gene)} patients fully paired | "
          f"selected {len(df)} = {df['size_mb'].sum():.0f} MB")

for cancer, df in slide_manifests.items():
    out_dir = f"{WORK}/svs/{cancer}"
    os.makedirs(out_dir, exist_ok=True)
    for _, row in df.iterrows():
        dest = f"{out_dir}/{row['patient_id']}.svs"
        if os.path.exists(dest):
            continue
        print(f"  {cancer} {row['patient_id']} ({row['size_mb']:.0f} MB)")
        with requests.get(f"{GDC_DATA}/{row['file_id']}", stream=True) as r:
            r.raise_for_status()
            with open(dest, "wb") as f:
                for chunk in r.iter_content(chunk_size=1 << 20):
                    f.write(chunk)

!du -sh {WORK}/svs/*

from google.colab import drive
import os, shutil

drive.mount('/content/drive')
BACKUP = "/content/drive/MyDrive/pamt_backup"
os.makedirs(BACKUP, exist_ok=True)

# Small, expensive to re-fetch (Drive rate-limits gdown)
for f in [f"{WORK}/dino_pamt_20cancer.pth", PATHWAY_CSV]:
    if os.path.exists(f) and not os.path.exists(f"{BACKUP}/{os.path.basename(f)}"):
        shutil.copy(f, BACKUP)
        print("backed up:", os.path.basename(f))

# Gene branch artifacts (~65 MB total)
os.makedirs(f"{BACKUP}/gene", exist_ok=True)
for cancer in CANCER_TYPES:
    gene_aligned[cancer].to_pickle(f"{BACKUP}/gene/gene_{cancer}.pkl")
    survival_data[cancer].to_pickle(f"{BACKUP}/gene/surv_{cancer}.pkl")
    np.save(f"{BACKUP}/gene/Eprime_{cancer}.npy", pathway_matrices[cancer])

print("\nbacked up:")
!du -sh {BACKUP}/*

import openslide
from skimage.filters import threshold_otsu
from scipy import ndimage as ndi
from PIL import Image


def pick_level_for_magnification(slide, target_mag=TARGET_MAG):
    """Return (level, effective_magnification) closest to target_mag."""
    obj = slide.properties.get(openslide.PROPERTY_NAME_OBJECTIVE_POWER)
    obj = float(obj) if obj else 40.0            # TCGA default when unlabelled
    want_downsample = obj / target_mag           # 40X -> 20X means downsample 2
    level = slide.get_best_level_for_downsample(want_downsample)
    actual = obj / slide.level_downsamples[level]
    return level, actual, obj


def build_tissue_mask(slide, target_downsample=MASK_LEVEL_TARGET):
    """Otsu on HSV saturation, then closing and small-object removal.

    Returns (mask, downsample_factor) where mask is a boolean array and
    downsample_factor maps mask coordinates to level-0 pixels.
    """
    lvl = slide.get_best_level_for_downsample(target_downsample)
    ds  = slide.level_downsamples[lvl]
    thumb = slide.read_region((0, 0), lvl, slide.level_dimensions[lvl]).convert("RGB")

    sat = np.array(thumb.convert("HSV"))[:, :, 1]
    thr = threshold_otsu(sat)
    mask = sat > thr

    # fill holes inside tissue, then drop specks
    mask = ndi.binary_closing(mask, structure=np.ones((5, 5)))
    mask = ndi.binary_fill_holes(mask)
    lab, n = ndi.label(mask)
    if n:
        sizes = ndi.sum(mask, lab, range(1, n + 1))
        keep = np.zeros(n + 1, bool)
        keep[1:][sizes >= 64] = True
        mask = keep[lab]

    return mask, ds, thr


def tissue_patch_coords(mask, mask_ds, level_ds, patch_size=PATCH_SIZE,
                        min_cover=MIN_TISSUE_COVER):
    """Grid the mask and return level-0 coordinates of tissue-covered patches."""
    # how many mask pixels one patch spans
    patch_in_mask = max(1, int(round(patch_size * level_ds / mask_ds)))
    step_level0   = int(round(patch_size * level_ds))

    coords = []
    for my in range(0, mask.shape[0] - patch_in_mask + 1, patch_in_mask):
        for mx in range(0, mask.shape[1] - patch_in_mask + 1, patch_in_mask):
            tile = mask[my:my + patch_in_mask, mx:mx + patch_in_mask]
            if tile.mean() >= min_cover:
                coords.append((int(mx * mask_ds), int(my * mask_ds)))
    return coords, step_level0


def extract_patches(svs_path, target=PATCH_TARGET, seed=SEED, show=False):
    slide = openslide.OpenSlide(svs_path)
    level, actual_mag, obj = pick_level_for_magnification(slide)
    level_ds = slide.level_downsamples[level]

    # Not every pyramid contains an exact 20X level. openslide returns the
    # largest level whose downsample does not exceed what we asked for, so a
    # 40X slide with levels [1, 4, 16] yields level 0 at 40X. In that case read
    # a proportionally larger region and resize down, which reproduces the
    # paper's 20X field of view rather than silently using 40X.
    scale = actual_mag / TARGET_MAG            # 1.0 when the level is already 20X
    read_size = int(round(PATCH_SIZE * scale))

    mask, mask_ds, thr = build_tissue_mask(slide)
    coords, _ = tissue_patch_coords(mask, mask_ds, level_ds)

    print(f"  scanned at {obj:.0f}X native -> level {level} = {actual_mag:.1f}X"
          f"{'' if abs(scale - 1) < 0.01 else f', reading {read_size}px and resizing to {PATCH_SIZE}px'}"
          f" | mask {mask.shape} (otsu {thr}) | {len(coords)} tissue positions")

    rng = np.random.default_rng(seed)
    rng.shuffle(coords)
    coords = coords[:target]

    patches = []
    for (x, y) in coords:
        region = slide.read_region((x, y), level, (read_size, read_size)).convert("RGB")
        if read_size != PATCH_SIZE:
            region = region.resize((PATCH_SIZE, PATCH_SIZE), Image.BILINEAR)
        patches.append((x, y, region))

    if show:
        thumb = slide.get_thumbnail((900, 900))
        fig, ax = plt.subplots(1, 2, figsize=(15, 6))
        ax[0].imshow(thumb); ax[0].set_title(
            f"WSI  {slide.dimensions[0]} x {slide.dimensions[1]}"); ax[0].axis("off")
        ax[1].imshow(mask, cmap="gray"); ax[1].set_title(
            f"tissue mask  (Otsu on saturation, thr={thr})"); ax[1].axis("off")
        plt.tight_layout(); plt.show()

    slide.close()
    return patches


# demo on the first available slide
_demo = sorted(glob.glob(f"{WORK}/svs/*/*.svs"))[0]
print("demo slide:", os.path.basename(_demo))
demo_patches = extract_patches(_demo, target=200, show=True)

fig, axes = plt.subplots(3, 6, figsize=(15, 8))
for ax, (x, y, img) in zip(axes.ravel(), demo_patches[:18]):
    ax.imshow(img); ax.axis("off")
for ax in axes.ravel()[len(demo_patches[:18]):]:
    ax.axis("off")
plt.suptitle(f"Mask-guided patches at {TARGET_MAG}X, {PATCH_SIZE}x{PATCH_SIZE}", fontsize=13)
plt.tight_layout(); plt.show()

from torchvision import transforms

device = "cuda" if torch.cuda.is_available() else "cpu"
print("DEVICE:", device)

# architecture only; weights come from the authors' checkpoint below
dino = torch.hub.load("facebookresearch/dino:main", "dino_vits8", pretrained=False)


def load_dino_checkpoint(model, ckpt_path):
    # PyTorch 2.6 defaults weights_only=True, which rejects the training
    # metadata (epoch, args) that main_dino.py saves alongside the weights.
    ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=False)

    if isinstance(ckpt, dict):
        print("  checkpoint top-level keys:", list(ckpt.keys())[:10])

    for key in ("teacher", "student", "model", "state_dict"):
        if isinstance(ckpt, dict) and key in ckpt:
            ckpt = ckpt[key]
            print(f"  using '{key}' weights")
            break

    ckpt = {k.replace("module.", "").replace("backbone.", ""): v
            for k, v in ckpt.items()}

    missing, unexpected = model.load_state_dict(ckpt, strict=False)
    print(f"  loaded | missing {len(missing)} | unexpected {len(unexpected)}")
    if len(missing) > 20:
        print("  WARNING: many missing keys, may not match ViT-S/8")
        print("  first missing:", missing[:5])
    return model


# THIS LINE IS THE ONE THAT WENT MISSING
dino = load_dino_checkpoint(dino, DINO_CKPT)
dino = dino.eval().to(device)

# verify the model actually landed on the GPU
model_device = next(dino.parameters()).device
print(f"model device: {model_device}")
assert str(model_device).startswith(device), \
    f"model is on {model_device} but inputs will be on {device}"

preprocess = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])


def embed_patches(patches, bs=32):
    out = []
    with torch.no_grad():
        for i in range(0, len(patches), bs):
            imgs = torch.stack([preprocess(p[2]) for p in patches[i:i+bs]]).to(device)
            out.append(dino(imgs).cpu().numpy())
            print(f"    {min(i+bs, len(patches))}/{len(patches)}", end="\r")
    return np.concatenate(out, axis=0)


t0 = time.time()
_test = embed_patches(demo_patches[:32])
dt = time.time() - t0
print(f"\nfeature shape: {_test.shape}   (expect (32, 384))")
print(f"32 patches in {dt:.1f}s  ->  {PATCH_TARGET} patches "
      f"~= {dt*PATCH_TARGET/32/60:.1f} min per slide")

from sklearn.cluster import KMeans

os.makedirs(f"{WORK}/features", exist_ok=True)
wsi_index = []          # one row per augmented sample

for cancer in CANCER_TYPES:
    for svs_path in sorted(glob.glob(f"{WORK}/svs/{cancer}/*.svs")):
        patient_id = os.path.splitext(os.path.basename(svs_path))[0]
        print(f"\n=== {cancer} / {patient_id} ===")

        patches = extract_patches(svs_path, target=PATCH_TARGET)
        if len(patches) < K_CLUSTERS:
            print("  too few tissue patches, skipping")
            continue

        embeddings = embed_patches(patches)
        print(f"\n  embeddings {embeddings.shape}")

        K = min(K_CLUSTERS, len(embeddings))
        labels = KMeans(n_clusters=K, n_init=20, random_state=SEED).fit_predict(embeddings)
        cluster_idx = [np.where(labels == c)[0] for c in range(K)]

        # G=80 independent selections -> G augmented input sequences
        rng = np.random.default_rng(SEED)
        seqs = []
        for g in range(G_AUGMENT):
            sel = []
            for idx in cluster_idx:
                if len(idx):
                    sel.extend(rng.choice(idx, min(PATCHES_PER_CLUST, len(idx)),
                                          replace=False).tolist())
            seqs.append(embeddings[np.array(sel)])

        out_npz = f"{WORK}/features/{cancer}_{patient_id}.npz"
        np.savez_compressed(
            out_npz,
            sequences=np.stack([s for s in seqs if len(s) == len(seqs[0])]),
            coords=np.array([(p[0], p[1]) for p in patches]),
            labels=labels,
        )
        wsi_index.append({"cancer": cancer, "patient_id": patient_id,
                          "n_patches": len(patches), "seq_len": seqs[0].shape[0],
                          "n_aug": len(seqs), "path": out_npz})
        print(f"  saved {len(seqs)} augmented sequences of {seqs[0].shape[0]} patches")

wsi_index = pd.DataFrame(wsi_index)
print("\n", wsi_index.to_string(index=False))

from google.colab import drive
import os, glob, shutil
import numpy as np

drive.mount('/content/drive')
BACKUP = "/content/drive/MyDrive/pamt_backup"
os.makedirs(f"{BACKUP}/features", exist_ok=True)
os.makedirs(f"{BACKUP}/gene", exist_ok=True)

# 1. Drive-rate-limited downloads, expensive to re-fetch
for f in [DINO_CKPT, PATHWAY_CSV]:
    dst = f"{BACKUP}/{os.path.basename(f)}"
    if os.path.exists(f) and not os.path.exists(dst):
        shutil.copy(f, dst); print("backed up:", os.path.basename(f))

# 2. Gene branch (~65 MB)
for cancer in CANCER_TYPES:
    gene_aligned[cancer].to_pickle(f"{BACKUP}/gene/gene_{cancer}.pkl")
    survival_data[cancer].to_pickle(f"{BACKUP}/gene/surv_{cancer}.pkl")
    np.save(f"{BACKUP}/gene/Eprime_{cancer}.npy", pathway_matrices[cancer])

# 3. Computed features (~3 MB per patient, the expensive part)
!cp -n {WORK}/features/*.npz {BACKUP}/features/ 2>/dev/null

n = len(glob.glob(f"{BACKUP}/features/*.npz"))
print(f"\n{n} patients backed up")
!du -sh {BACKUP}/*

from sklearn.model_selection import KFold

cv_splits = {}
for cancer in CANCER_TYPES:
    patients = sorted(set(wsi_index[wsi_index.cancer == cancer].patient_id))
    if len(patients) < 5:
        print(f"{cancer}: only {len(patients)} patients, 5-fold CV not meaningful")
        continue
    kf = KFold(n_splits=5, shuffle=True, random_state=SEED)
    cv_splits[cancer] = [{"train": [patients[i] for i in tr],
                          "test":  [patients[i] for i in te]}
                         for tr, te in kf.split(patients)]
    print(f"{cancer}: 5-fold CV over {len(patients)} patients "
          f"({len(cv_splits[cancer][0]['train'])} train / "
          f"{len(cv_splits[cancer][0]['test'])} test per fold)")

os.makedirs(f"{WORK}/final", exist_ok=True)
manifest = []

for _, row in wsi_index.iterrows():
    cancer, pid = row["cancer"], row["patient_id"]
    if pid not in gene_aligned[cancer].index or pid not in survival_data[cancer].index:
        print(f"  {pid}: missing gene or survival data, skipping")
        continue

    E = build_pathway_tokens(cancer, pid)
    gene_path = f"{WORK}/final/gene_{cancer}_{pid}.npy"
    np.save(gene_path, E)

    manifest.append({
        "cancer": cancer, "patient_id": pid,
        "gene_tokens": gene_path, "gene_shape": str(E.shape),
        "wsi_features": row["path"], "n_augmented": row["n_aug"],
        "seq_len": row["seq_len"],
        "time_days": float(survival_data[cancer].loc[pid, "time_days"]),
        "event": int(survival_data[cancer].loc[pid, "event"]),
    })

manifest = pd.DataFrame(manifest)
manifest.to_csv(f"{WORK}/final/manifest.csv", index=False)
with open(f"{WORK}/final/cv_splits.json", "w") as f:
    json.dump(cv_splits, f, indent=2)

print("=" * 70)
print("PAMT PREPROCESSING COMPLETE (Sections III-A + III-B)")
print("=" * 70)
print(manifest[["cancer", "patient_id", "gene_shape", "seq_len",
                "n_augmented", "time_days", "event"]].to_string(index=False))
print(f"\npaired patients : {len(manifest)}")
print(f"training samples: {manifest['n_augmented'].sum()}")
print(f"deaths observed : {manifest['event'].sum()} / {len(manifest)}")
print("=" * 70)

!cp -n {WORK}/final/*.npy {WORK}/final/*.csv {WORK}/final/*.json {BACKUP}/final/ 2>/dev/null || \
 (mkdir -p {BACKUP}/final && cp -n {WORK}/final/* {BACKUP}/final/)
!cp -n {WORK}/features/*.npz {BACKUP}/features/ 2>/dev/null
!du -sh {BACKUP}/*

m = pd.read_csv(f"{WORK}/final/manifest.csv")
row = m.iloc[0]

gene_tokens = np.load(row["gene_tokens"])

d = np.load(row["wsi_features"])
print("npz keys:", list(d.keys()))

if "sequences" in d:                       # full-sequence format
    wsi_tokens = d["sequences"][0]
else:                                      # embeddings + indices format
    wsi_tokens = d["embeddings"][d["selection_indices"][0]]

print(f"\npatient    : {row['patient_id']} ({row['cancer']})")
print(f"GENE branch: {gene_tokens.shape}   (186 pathway tokens)")
print(f"WSI  branch: {wsi_tokens.shape}   (patch tokens, 384-d)")
print(f"survival   : {row['time_days']:.0f} days, event={row['event']}")
print(f"{row['n_augmented']} augmented sequences available")

import numpy as np, pandas as pd, os, glob
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

m   = pd.read_csv(f"{WORK}/final/manifest.csv")
row = m.iloc[0]
cancer, pid = row["cancer"], row["patient_id"]

d           = np.load(row["wsi_features"])
gene_tokens = np.load(row["gene_tokens"])
wsi_tokens  = d["sequences"][0] if "sequences" in d else \
              d["embeddings"][d["selection_indices"][0]]
coords, labels = d["coords"], d["labels"]

print(f"patient {pid} ({cancer}) | GENE {gene_tokens.shape} | WSI {wsi_tokens.shape}")


# ============================================================ OUTPUT 1
svs = f"{WORK}/svs/{cancer}/{pid}.svs"
if os.path.exists(svs):
    import openslide
    sl = openslide.OpenSlide(svs)
    plt.figure(figsize=(11, 8))
    plt.imshow(sl.get_thumbnail((1100, 1100)))
    plt.title(f"OUTPUT 1 — Whole Slide Image\n{pid} ({cancer}), "
              f"{sl.dimensions[0]:,} x {sl.dimensions[1]:,} px", fontsize=13)
    plt.axis("off"); plt.tight_layout(); plt.show()
    sl.close()
else:
    print("OUTPUT 1 skipped: SVS not on disk (not backed up to Drive).")
    print("Re-run Cells 7-8 to fetch it if you need the thumbnail.")


# ============================================================ OUTPUT 2
selected = set(d["selection_indices"][0]) if "selection_indices" in d else set()

fig, ax = plt.subplots(1, 2, figsize=(17, 7))

ax[0].scatter(coords[:, 0], coords[:, 1], c=labels, cmap="tab20", s=14, marker="s")
ax[0].invert_yaxis(); ax[0].set_aspect("equal")
ax[0].set_title(f"K-means clustering, K=50\n{len(coords)} patches on WSI coordinates")
ax[0].set_xlabel("x (px)"); ax[0].set_ylabel("y (px)")

if selected:
    mask = np.array([i in selected for i in range(len(coords))])
    ax[1].scatter(coords[~mask, 0], coords[~mask, 1], c="lightgrey", s=10, marker="s")
    ax[1].scatter(coords[mask, 0], coords[mask, 1],
                  c=labels[mask], cmap="tab20", s=22, marker="s")
    ax[1].set_title(f"Selected sequence: {mask.sum()} of {len(coords)}\n"
                    "S=10 sampled per cluster")
else:
    sizes = np.bincount(labels, minlength=50)
    ax[1].bar(range(len(sizes)), sizes, color="steelblue")
    ax[1].axhline(10, color="red", ls="--", label="S = 10 sampled per cluster")
    ax[1].set_title("Cluster sizes"); ax[1].set_xlabel("cluster id"); ax[1].legend()
ax[1].invert_yaxis() if selected else None
ax[1].set_aspect("equal") if selected else None

plt.suptitle(f"OUTPUT 2 — Patch clustering and selection ({pid})", fontsize=14)
plt.tight_layout(); plt.show()


# ============================================================ OUTPUT 3
fig, ax = plt.subplots(1, 2, figsize=(16, 6),
                       gridspec_kw={"width_ratios": [2.4, 1]})

sub = gene_tokens[:, :500]
v   = np.abs(sub[sub != 0]).max() if (sub != 0).any() else 1
im  = ax[0].imshow(sub, aspect="auto", cmap="RdBu_r", vmin=-v, vmax=v,
                   interpolation="nearest")
ax[0].set_title("E = E' ⊙ e   (first 500 of "
                f"{gene_tokens.shape[1]} genes)\n"
                "red = high expression, blue = low, white = not in pathway")
ax[0].set_xlabel("gene index"); ax[0].set_ylabel("pathway index (P1 … P186)")
plt.colorbar(im, ax=ax[0], label="z-score")

nz = (gene_tokens != 0).sum(1)
ax[1].hist(nz, bins=30, color="steelblue", edgecolor="white")
ax[1].axvline(nz.mean(), color="red", ls="--", label=f"mean {nz.mean():.0f}")
ax[1].set_title("genes per pathway"); ax[1].set_xlabel("non-zero genes")
ax[1].legend()

plt.suptitle(f"OUTPUT 3 — Pathway-based gene expression matrix {gene_tokens.shape}",
             fontsize=14)
plt.tight_layout(); plt.show()

print(f"sparsity: {(gene_tokens == 0).mean():.1%} "
      f"(most genes belong to no given pathway, so most entries are zero)")


# ============================================================ OUTPUT 4
fig = plt.figure(figsize=(16, 6))
gs  = fig.add_gridspec(1, 3, width_ratios=[2.2, 1, 1.1], wspace=0.3)

a0 = fig.add_subplot(gs[0])
a0.imshow(gene_tokens[:, :600], aspect="auto", cmap="RdBu_r",
          vmin=-v, vmax=v, interpolation="nearest")
a0.set_title(f"GENE branch\n{gene_tokens.shape}  →  186 pathway tokens")
a0.set_ylabel("pathway"); a0.set_xlabel("gene")

a1 = fig.add_subplot(gs[1])
a1.imshow(wsi_tokens, aspect="auto", cmap="viridis", interpolation="nearest")
a1.set_title(f"WSI branch\n{wsi_tokens.shape}  →  {wsi_tokens.shape[0]} patch tokens")
a1.set_ylabel("patch"); a1.set_xlabel("DINO feature (384-d)")

a2 = fig.add_subplot(gs[2]); a2.axis("off")
a2.text(0.5, 0.5,
        "PAIRED INPUT, READY FOR FUSION\n\n"
        f"patient   {pid}  ({cancer})\n"
        f"survival  {row['time_days']:.0f} days, event = {row['event']}\n"
        f"augment   {row['n_augmented']} sequences\n\n"
        "── Section III-C, NOT BUILT ──\n"
        "Transformer encoders\n"
        "→ contrastive alignment (L3)\n"
        "→ pathway-to-patch cross-attention\n"
        f"→ attention matrix (186 × {wsi_tokens.shape[0]})\n"
        "→ MLP → survival risk R",
        ha="center", va="center", fontsize=10, family="monospace",
        bbox=dict(boxstyle="round,pad=0.8", facecolor="#f2f2f2", edgecolor="#999"))

plt.suptitle("OUTPUT 4 — Paired multimodal input (Sections III-A + III-B complete)",
             fontsize=14)
plt.tight_layout(); plt.show()

import numpy as np, os, glob
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.cluster import KMeans
import openslide

# ---- pick a slide (must still be on disk) ----
svs_files = sorted(glob.glob(f"{WORK}/svs/*/*.svs"))
assert svs_files, "No SVS on disk. Re-run Cells 7-8 to fetch one."
svs_path = svs_files[0]
cancer   = svs_path.split("/")[-2]
pid      = os.path.splitext(os.path.basename(svs_path))[0]
print(f"slide: {pid} ({cancer})")

TARGET_TILES = 4000     # raise for finer detail, costs embedding time

slide = openslide.OpenSlide(svs_path)
level, actual_mag, obj = pick_level_for_magnification(slide)
level_ds = slide.level_downsamples[level]
scale     = actual_mag / TARGET_MAG
read_size = int(round(PATCH_SIZE * scale))

mask, mask_ds, thr = build_tissue_mask(slide)
print(f"mask {mask.shape}, {mask.sum():,} tissue pixels")

# ---- choose a stride giving roughly TARGET_TILES uniform tiles ----
base = max(1, int(round(PATCH_SIZE * level_ds / mask_ds)))
step = base
while True:
    n = sum(mask[y:y+step, x:x+step].mean() >= 0.5
            for y in range(0, mask.shape[0]-step+1, step)
            for x in range(0, mask.shape[1]-step+1, step))
    if n <= TARGET_TILES or step > base * 20:
        break
    step += max(1, base // 4)
print(f"stride {step}px in mask space -> {n} tiles covering the whole tissue")

cells = [(y, x) for y in range(0, mask.shape[0]-step+1, step)
                for x in range(0, mask.shape[1]-step+1, step)
                if mask[y:y+step, x:x+step].mean() >= 0.5]

# ---- read + embed every tile ----
patches = []
for (my, mx) in cells:
    x0, y0 = int(mx * mask_ds), int(my * mask_ds)
    reg = slide.read_region((x0, y0), level, (read_size, read_size)).convert("RGB")
    if read_size != PATCH_SIZE:
        reg = reg.resize((PATCH_SIZE, PATCH_SIZE), Image.BILINEAR)
    patches.append((x0, y0, reg))
print(f"read {len(patches)} tiles, embedding...")

emb    = embed_patches(patches)
labels = KMeans(n_clusters=50, n_init=20, random_state=SEED).fit_predict(emb)
print(f"\nembedded {emb.shape}, clustered into 50 groups")

# ---- paint labels into a solid image at mask resolution ----
lab_img = np.full(mask.shape, -1, np.int16)
for (my, mx), L in zip(cells, labels):
    lab_img[my:my+step, mx:mx+step] = L

thumb = slide.get_thumbnail((mask.shape[1], mask.shape[0]))
slide.close()

cmap = ListedColormap(plt.cm.tab20(np.linspace(0, 1, 20)).tolist() * 3)
disp = np.ma.masked_where(lab_img < 0, lab_img)

# ---- vertical layout, matching the paper's figure ----
fig, ax = plt.subplots(2, 1, figsize=(6.5, 12))

ax[0].imshow(thumb)
ax[0].set_title("Whole slide image", fontsize=13, style="italic")
ax[0].axis("off")

ax[1].imshow(disp, cmap=cmap, interpolation="nearest")
ax[1].set_title(f"Patch clustering  (K=50, {len(cells)} patches)", fontsize=13)
ax[1].axis("off")

fig.text(0.5, 0.503, "Patch\nclustering  ⬇", ha="center", va="center",
         fontsize=12, family="serif")

plt.suptitle(f"{pid}  ({cancer})", fontsize=12, y=0.995)
plt.tight_layout(rect=[0, 0, 1, 0.985])
plt.savefig(f"{WORK}/final/clustering_{cancer}_{pid}.png", dpi=200,
            bbox_inches="tight")
plt.show()

print(f"\nsaved: {WORK}/final/clustering_{cancer}_{pid}.png")